### ISSUE TITLE
remove stock

### ISSUE THREAD

**Issue by CFox243** [inventree/inventree-app#479]
OK, am I being dumb or what...

when in the app or web doesn't matter
when I remove stock it asks for an amount and notes.
However when the transaction completes where do I go to see the log/account of the item being removed with the note?

**Comment by CFox243** [comment]
im trying to figure out if this is a mock-up or a real feature i cant find.
![inventree stock](https://github.com/inventree/inventree-app/assets/128409855/74290527-d240-4e2f-9108-466abf157c24)

https://github.com/inventree/InvenTree/issues/1303#issuecomment-1995949012

**Comment by SchrodingersGat** [comment]
@CFox243 just tried this on the demo site, it works just fine:

Here you can see the history after I manually removed some stock

![image](https://github.com/inventree/inventree-app/assets/10080325/9d6fe989-cf7c-4df6-bf0f-6f45af4799cf)

**Comment by CFox243** [comment]
@SchrodingersGat 
I guess I'm just lost on how to pull that screen up. when I navigate to a part in stock it auto redirects to the part section, not stock. all I see is
![image](https://github.com/inventree/inventree-app/assets/128409855/bffa20ed-630b-4a13-9142-c959cafa5a14)

if i type in your url exactly i can see it but not sure how you are getting there without hand typing /stock/item/408/#
i have to be missing something
Thank you for your assistance on this

**Comment by wolflu05** [comment]
Yes, that's a bit tricky to discover, but if you click on the "Stock" column with the number you get to the stock items detail page.

![image](https://github.com/inventree/inventree-app/assets/76838159/f72b7db9-f9c2-4694-a6d0-731aac7584bd)
 
That's why we changed this with the new UI (Platform UI). There you can click on the complete column to get to the stock items detail page

<details><summary>PUI Image</summary>

![image](https://github.com/inventree/inventree-app/assets/76838159/1214ff53-cc31-4097-b855-42e6b9a874ef)

</details>

**Comment by CFox243** [comment]
Thank you right in front of me the whole time. thank you for yalls assistance.
